name: Lint & Auto-Fix

on:
  push:
    branches: [main, Sdev, bdev]
  pull_request:
    branches: [main, Sdev, bdev]

jobs:
  lint-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint and fix issues
        run: npx eslint . --fix

      - name: Run Prettier and fix issues
        run: npx prettier --write .

      - name: Commit and push fixes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Auto-fix: ESLint & Prettier applied" || exit 0
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
